name: CI

on:
  push:
    branches:
      - "*"
jobs:
  test:
    name: validate and test code
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup java JDK
        uses: actions/setup-java@v3
        with:
          java-version: 11

      - name: Cache the Maven packages to speed up build
        uses: actions/cache@v1
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2

      - name: Checkstyle
        run: mvn checkstyle:checkstyle

      - name: Compile application
        run: mvn compile

      - name: MongoDB in GitHub Actions
        uses: supercharge/mongodb-github-action@1.7.0

      - name: Run tests and verify security
        run: mvn verify

      - name: Cache SonarCloud packages
        uses: actions/cache@v1
        with:
          path: ~/.sonar/cache
          key: ${{ runner.os }}-sonar
          restore-keys: ${{ runner.os }}-sonar
      - name: Cache Maven packages
        uses: actions/cache@v1
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2
      - name: Analyze code quality
        env:
          GITHUB_TOKEN: ${{ secrets.AUTH_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: mvn -B verify org.sonarsource.scanner.maven:sonar-maven-plugin:sonar -Dsonar.projectKey=GLO2003-H22-eq11_H22-projet -Dsonar.host.url=https://sonarcloud.io/ -Dsonar.organization=glo2003-h22-eq11 